<h1 style="color:#009345">Renewables</h1>

<p>Over the last few years the demand for the installation of solar energy systems has increased, our engineers have experience and a comprehensive knowledge of these systems.</p>

<p>We can provide expert advice on which system to have installed, the best configuration and all the aspects that you need to take into consideration when purchasing renewable energy systems.</p>

<h2 style="color:#009345">Solar Panels</h2>

<p>Solar electricity is captured from the sun through photovoltaic cells converting the sunlight into electricity which is used to operate all your household appliances and lighting. Even on a cloudy day electricity can still be generated as the PV cells don’t require direct sunlight. There are two types of solar water heating panels, evacuated tubes and flat plate collectors. Flat plates collectors can be fixed on the roof tiles or integrated into the roof and will capture heat from the sun to heat water and create electricity</p>

<h2 style="color:#009345">Air source heating and heat pumps</h2>

<p>Heat pumps which are also environmentally friendly require electricity to run, however this can be be generated by solar panels to provide a complete efficient and environmental system.</p>

<p>Air source heat pumps extract heat from the outside air even in low temperatures of -15º C, this heat can be used for radiator, warm air convectors, underfloor heating and hot water.</p>


