<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>This domain has been registered by BT</title>
</head>
<body>
<table border="0" cellpadding="0" cellspacing="0" width="596">
  <tbody>
    <tr> 
      <td colspan="4"><img src="images/domain_name_holding_logo.jpg" alt="www.bt.com" title="www.bt.com" height="52" width="88"></td>
    </tr>
    <tr> 
      <td colspan="4">&nbsp;</td>
    </tr>
    <tr> 
      <td colspan="4"><img src="images/domain_name_holding_header.gif" alt="This domain has been registered by BT" title="This domain has been registered by BT" height="50" width="596"></td>
    </tr>
    <tr> 
      <td colspan="4">&nbsp;</td>
    </tr>
    <tr> 
      <td colspan="4"><img src="images/domain_name_holding_01.gif" alt="Business grade web hosting from BT from just &amp;pound;5 per month (ex. VAT)" width="596" height="188"></td>
    </tr>
    <tr> 
      <td width="158"><img src="images/domain_name_holding_02.gif" alt="Visit us today to see our Web Hosting &amp; eCommerce solutions" width="158" height="20"></td>
      <td width="143"><a href="http://www.bt.com/business/help/webhosting/" target="_blank"><img src="images/domain_name_holding_03.gif" alt="www.bt.com/webhosting" width="143" height="20" border="0"></a></td>
      <td width="169"><img src="images/domain_name_holding_04.gif" width="169" height="20"></td>
      <td width="126"><a href="http://www.bt.com/business/help/webhosting/" target="_blank"><img src="images/domain_name_holding_05.gif" alt="Find out more" width="126" height="20" border="0"></a></td>
    </tr>
    <tr> 
      <td colspan="4"><img src="images/domain_name_holding_06.gif" width="596" height="19"></td>
    </tr>
  </tbody>
</table>


</body></html>